spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mottu}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: false
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: true
  h2:
    console:
      enabled: false

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN

server:
  forward-headers-strategy: framework

